language: python
python:
   - "2.7"
before_install:
   # Move out of git directory to build root.
   - deactivate
   - cd ../..
   - pwd
install:
   # Download and extract the prebuilt binary.
   - wget -O nanshe-package.tgz https://www.dropbox.com/s/qhy2lhsk0ioge0p/nanshe-package.tgz?dl=0
   - tar -xzf nanshe-package.tgz
   - ls
   # Replace the src in the prebuilt binary with the one TravisCI cloned for us.
   - rm -rf nanshe-package.tgz
   - rm -rf nanshe-package/src/nanshe-git
   - mv $TRAVIS_REPO_SLUG nanshe-package/src/nanshe-git
   # Activate the environment.
   - cd nanshe-package
   - export BUILDEM_DIR=$(pwd)
   - echo "\$BUILDEM_DIR = ${BUILDEM_DIR}"
   - source $BUILDEM_DIR/bin/setenv_ilastik_gui.sh
   # Install coverage and coveralls to generate and submit test coverage results for coveralls.io. Also, install docstring-coverage to get information about documentation coverage.
   - python $BUILDEM_DIR/bin/pip install coverage
   - python $BUILDEM_DIR/bin/pip install docstring-coverage
   - python $BUILDEM_DIR/bin/pip install python-coveralls
   # Won't recognize setup.cfg unless we are in the source directory.
   - cd src/nanshe-git
script:
   # Run tests. Skip 3D tests as they take too long (~1hr).
   - python $BUILDEM_DIR/bin/nosetests --with-coverage --cover-erase --cover-branches --cover-package=nanshe -a '!3D','!DRMAA'
   # Build documentation.
   - cd docs
   # Unfortunately, this does not seem to work on TravisCI. This is because sphinx-apidoc cannot be found when in the Makefile. However, it is easily and correctly found right before the call. This may be related to a more general issue ( https://github.com/travis-ci/travis-ci/issues/3084 ). As a consequence, we will just copy code from the Makefile for now.
   # - make html
   - python $BUILDEM_DIR/bin/sphinx-apidoc -f -T -e -M -o . .. ../setup.py ../tests
   - python $BUILDEM_DIR/bin/sphinx-build -b html -d _build/doctrees . _build/html
   # Move back to source directory.
   - cd ..
   # Get info on docstring coverage.
   - python $BUILDEM_DIR/bin/docstring-coverage nanshe | tee .docstring-coverage
after_success:
   # Submit results to coveralls.io.
   - python $BUILDEM_DIR/bin/coveralls
   # Check to see if this is the right branch to build documentation from.
   - if [ $TRAVIS_PULL_REQUEST != "false" ]; then exit 0 ; fi
   - if [ $TRAVIS_BRANCH != "master" ]; then exit 0 ; fi
   # Save documentation and documentation coverage statistics.
   - mv docs/_build/html ../nanshe-git-docs
   - mv .docstring-coverage ../nanshe-git-docs
   # Update credentials
   - git config --global user.name "Travis CI"
   - git config --global user.email "noreply@travis-ci.org"
   # Get current pages. Unfortunately, `git fetch` does not work here.
   - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
   - git checkout --orphan gh-pages
   - git pull origin gh-pages
   - git branch -v
   # Save important git files.
   - mv .git ../nanshe-git-docs/
   - mv .nojekyll ../nanshe-git-docs/
   # Replace old documentation with new documentation.
   - rm -rf * .*
   - mv ../nanshe-git-docs/.nojekyll .
   - mv ../nanshe-git-docs/.git .
   - mv ../nanshe-git-docs/.docstring-coverage .
   - mv ../nanshe-git-docs/* .
   - rm -rf ../nanshe-git-docs
   # Commit changes and push. Reference commit used and tag if relevant.
   - git add -A
   - if [ -z $TRAVIS_TAG ]; then git commit -m "Rebuilt documentation for commit (${TRAVIS_COMMIT})." --allow-empty ; else git commit -m "Rebuilt documentation for commit (${TRAVIS_COMMIT}) and tag (${TRAVIS_TAG})." --allow-empty ; fi
   - git push origin gh-pages
env:
   global:
       secure: gCN4vEn/1pKi+N9+00E8Ju+ImKpizdoblkSFnBr8TCXRWY4/iKM4yNkX/YtYsNwzh0eCq+840CXRYlcodG9nilG23RmubKZ1Y+T2fuFoEQbzE5QmPB7+fl01dlLpDbDtN6L7VSOtfjOj8BQGkdR9VwBMomseWgY37yuTnErfxeU=
# Use container format for TravisCI to avoid termination due to insufficient resources.
sudo: false
